### ISSUE TITLE
RuntimeException: Could not invoke RNInAppBrowser.open

### ISSUE THREAD

**Issue by tonykolomeytsev** [steuerbot/android-sdk#11]
I encountered a bug when working with the SDK, the application crashes. These are the logs coming from the crashlytics:
```
Fatal Exception: java.lang.RuntimeException: Could not invoke RNInAppBrowser.open
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:17)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
       at java.lang.Thread.run(Thread.java:920)

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:14)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
       at java.lang.Thread.run(Thread.java:920)

Caused by java.lang.NoClassDefFoundError: Failed resolution of: Lorg/greenrobot/eventbus/EventBus;
       at com.proyecto26.inappbrowser.RNInAppBrowserModule.open(RNInAppBrowserModule.java:78)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:14)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
       at java.lang.Thread.run(Thread.java:920)

Caused by java.lang.ClassNotFoundException: org.greenrobot.eventbus.EventBus
       at com.proyecto26.inappbrowser.RNInAppBrowserModule.open(RNInAppBrowserModule.java:78)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:14)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
       at java.lang.Thread.run(Thread.java:920)
```

Looks like a problem with proguard-rules and R8 obfuscation. The problem is on different devices and different versions of android.

**Comment by friedolinfoerder** [comment]
Fixed with Version 2.13.0
